services:
  flask:
    build:
      context: ../flask-OCR-service  # Adjust the path to your Flask directory
      dockerfile: Dockerfile  
    image: flask-expense-tracker:latest
    container_name: flask_expense_tracker
    ports:
      - "5000:5000"
    env_file:
      - ../flask-OCR-service/.env  # Adjust the path to your Flask directory
    restart: always
    networks:
      - backend

  django:
    build:
        context: .
        dockerfile: Dockerfile
    image: django-expense-tracker:latest
    container_name: django_expense_tracker
    ports:
      - "8000:8000"
      - "5055:5055"
      - "5005:5005"
    depends_on:
      - flask_expense_tracker
    env_file:
      - .env
    restart: always
    networks:
      - backend
  
  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    restart: always
    networks:
      - backend

  networks:
    backend:
      driver: bridge
    